In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import plotly.express as px
import plotly.graph_objects as go

## Dataset Creation

In [ ]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [ ]:
df = pd.DataFrame({'feature_1':X[:,0], 'feature_2':X[:,1], 'target':y})

In [ ]:
df.shape

(100, 3)

In [ ]:
df.head()

   feature_1  feature_2      target
0   0.874717  -0.880911    1.192125
1   0.300580  -0.355925  -59.364888
2  -0.789106  -1.445770 -156.284786
3   1.587920  -1.038322   49.908800
4  -2.203155   1.146078 -174.581030

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature_1  100 non-null    float64
 1   feature_2  100 non-null    float64
 2   target     100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB

In [ ]:
df.describe()

        feature_1   feature_2      target
count  100.000000  100.000000  100.000000
mean    -0.235910    0.044876   -8.140936
std      0.982040    0.931217   74.102597
min     -2.627638   -2.889629 -174.581030
25%     -0.945822   -0.489077  -60.167433
50%     -0.182163    0.193152   -6.434636
75%      0.401344    0.629650   43.103882
max      2.104084    1.883143  191.240986

## 3D Plotting

In [ ]:
px.scatter_3d(df, x = 'feature_1', y = 'feature_2', z = 'target')

## Spliting Features

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Modeling

In [ ]:
mlr = LinearRegression()

In [ ]:
mlr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = mlr.predict(X_test)

## Regression Metrics

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mae

46.19095165161956

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mse

3127.184860242317

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

0.3180298725853805